server:
  port: 8080
  error:
    include-stacktrace: never
  servlet:
    context-path: /photo-app


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/photo_app
    username: postgres
    password: postgres
    platform: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database: postgresql

    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true


tokenSecret: karg-secret

ses: validatedemail@gmail.com