server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_management_db_dev
    username: postgres
    password: postgres
    platform: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true